# Generated by Django 5.2.6 on 2025-12-20 00:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_order', models.CharField()),
                ('description_of_order', models.TextField()),
                ('rate_for_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('data_giving', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Steamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_steamers', models.CharField()),
                ('last_name_steamers', models.CharField()),
                ('call_sign', models.CharField()),
                ('rank', models.CharField()),
                ('biography', models.TextField()),
                ('combat_experience', models.CharField()),
                ('joined_regiment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_private', models.CharField()),
                ('last_name_private', models.CharField()),
                ('call_sign', models.CharField()),
                ('rank', models.CharField()),
                ('biography', models.TextField()),
                ('university_education', models.CharField()),
                ('steamer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private', to='forum.steamer')),
            ],
        ),
    ]
