# Generated by Django 5.2.6 on 2026-01-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Private',
        ),
        migrations.DeleteModel(
            name='Steamer',
        ),
    ]
