# Generated by Django 5.2.6 on 2026-02-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_operation_circledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circledata',
            name='value',
        ),
    ]
