# Generated by Django 5.2.6 on 2026-02-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_circledata_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CircleData',
            new_name='CircleDataVOne',
        ),
    ]
