# Generated by Django 5.2.6 on 2026-02-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_circledata_circledatavone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CircleDataVOne',
            new_name='CircleData',
        ),
    ]
