# Generated by Django 5.2.6 on 2026-02-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_rename_circledatavone_circledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
