# Generated by Django 5.2.6 on 2026-02-27 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_operation_latitude_alter_operation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_giving',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
