# Generated by Django 5.2.6 on 2026-02-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_circledata_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circledata',
            name='created_by',
        ),
        migrations.AddField(
            model_name='circledata',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
