# Generated by Django 5.2.6 on 2026-02-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_circledata_created_by_circledata_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='circledata',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circledata',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
