# Generated by Django 5.2.6 on 2026-02-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_operation_latitude_remove_operation_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circledata',
            name='circle_id',
        ),
    ]
