# Generated by Django 5.2.6 on 2026-03-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_circledata_circle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rate_for_order',
        ),
    ]
