# Generated by Django 5.2.6 on 2026-03-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_remove_order_rate_for_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circledata',
            name='value',
        ),
    ]
