# Generated by Django 5.2.6 on 2026-03-05 22:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_remove_circledata_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiment', models.CharField(blank=True, choices=[('BA', 'British Army'), ('RAC', 'Royal Armoured Corps'), ('BMP', ' British Military Police'), ('RM', 'Royal Marines'), ('MPR', 'Military Parachute Regiment'), ('UKSF', 'United Kingdom Special Forces')], max_length=10, null=True)),
                ('description', models.TextField(max_length=200)),
                ('date_giving', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_recruits', models.PositiveIntegerField(default=10)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_selections', to=settings.AUTH_USER_MODEL)),
                ('recruits', models.ManyToManyField(blank=True, related_name='signed_up_to_selection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
