# Generated by Django 5.2.6 on 2026-03-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_regimentselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimentselection',
            name='regiment',
            field=models.CharField(blank=True, choices=[('RAC', 'Royal Armoured Corps'), ('BMP', ' British Military Police'), ('RM', 'Royal Marines'), ('MPR', 'Military Parachute Regiment'), ('UKSF', 'United Kingdom Special Forces')], max_length=10, null=True),
        ),
    ]
