# Generated by Django 5.2.6 on 2026-03-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_alter_regimentselection_regiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forum.reviewerofrequest'),
        ),
    ]
