# Generated by Django 5.2.6 on 2026-03-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_request_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerofrequest',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='forum.request'),
        ),
    ]
