# Generated by Django 5.2.6 on 2026-03-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_alter_reviewerofrequest_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.reviewerofrequest'),
        ),
        migrations.AlterField(
            model_name='reviewerofrequest',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='forum.request'),
        ),
    ]
