# Generated by Django 5.2.6 on 2026-04-26 15:59

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_order_published_by_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='document',
            field=models.ImageField(blank=True, help_text='Upload document image', null=True, upload_to='document_pictures/', validators=[forum.models.validate_document]),
        ),
    ]
