# Generated by Django 5.2.6 on 2026-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_officers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='regiment',
            field=models.CharField(blank=True, choices=[('BA', 'British Army'), ('RAC', 'Royal Armoured Corps'), ('BMP', ' British Military Police'), ('RM', 'Royal Marines'), ('MPR', 'Military Parachute Regiment'), ('UKSF', 'United Kingdom Special Forces')], default='BA', max_length=10, null=True),
        ),
    ]
