# Generated by Django 5.2.6 on 2026-01-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_officers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CTZ', 'Citizen'), ('PRESS', 'Journalist'), ('MLT', 'Military')], default='MLT', max_length=10),
        ),
    ]
