# Generated by Django 5.2.6 on 2026-01-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_officers', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, choices=[('RCT', 'Recruit'), ('PVT', 'Private'), ('LCPL', 'Lance Corporal'), ('CPL', 'Corporal'), ('SGT', 'Sergeant'), ('SSGT', 'Staff Sergeant'), ('WOC2', 'Warrant Officer Class 2'), ('WOC1', 'Warrant Officer Class 1'), ('2LT', 'Second Lieutenant'), ('LT', 'Lieutenant'), ('CPT', 'Captain'), ('MAJ', 'Major'), ('LTC', 'Lieutenant Colonel'), ('COL', 'Colonel'), ('BRIG', 'Brigadier'), ('MG', 'Major General'), ('LG', 'Lieutenant General'), ('GEN', 'General')], default='RCT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('CTZ', 'Citizen'), ('PRESS', 'Journalist'), ('MLT', 'Military')], default='MLT', max_length=10, null=True),
        ),
    ]
