# Generated by Django 5.2.6 on 2026-01-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_officers', '0003_alter_customuser_rank_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='regiment',
            field=models.CharField(blank=True, choices=[('BA', 'British Army'), ('RAC', 'Royal Armoured Corps'), ('BMP', ' British Military Police'), ('RM', 'Royal Marines'), ('AAB', 'Assault Airborne Battalion'), ('UKSF', 'United Kingdom Special Forces')], default='BA', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CTZ', 'Citizen'), ('PRESS', 'Journalist'), ('MLT', 'Military')], default='MLT', max_length=10),
        ),
    ]
